apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo-service
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.containerPort }}