apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "mongo-chart.fullname" . } }
spec:
  replicas: { { .Values.mongo.replicas } }
  selector:
    matchLabels:
      app: { { include "mongo-chart.name" . } }
  template:
    metadata:
      labels:
        app: { { include "mongo-chart.name" . } }
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          ports:
            - containerPort: { { .Values.mongo.containerPort } }
          resources:
            requests:
              memory: { { .Values.mongo.resources.requests.memory } }
              cpu: { { .Values.mongo.resources.requests.cpu } }
            limits:
              memory: { { .Values.mongo.resources.limits.memory } }
              cpu: { { .Values.mongo.resources.limits.cpu } }
